// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: classes.proto
// Protobuf Java Version: 4.29.0

package socket.data;


public final class Classes {
  private Classes() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      Classes.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PessoaProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:socket.data.PessoaProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nome = 1;</code>
     * @return The nome.
     */
    java.lang.String getNome();
    /**
     * <code>string nome = 1;</code>
     * @return The bytes for nome.
     */
    com.google.protobuf.ByteString
        getNomeBytes();

    /**
     * <code>string cidade = 2;</code>
     * @return The cidade.
     */
    java.lang.String getCidade();
    /**
     * <code>string cidade = 2;</code>
     * @return The bytes for cidade.
     */
    com.google.protobuf.ByteString
        getCidadeBytes();

    /**
     * <code>int64 telefone = 3;</code>
     * @return The telefone.
     */
    long getTelefone();

    /**
     * <code>int32 ano = 4;</code>
     * @return The ano.
     */
    int getAno();
  }
  /**
   * Protobuf type {@code socket.data.PessoaProto}
   */
  public static final class PessoaProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:socket.data.PessoaProto)
      PessoaProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "",
        PessoaProto.class.getName());
    }
    // Use PessoaProto.newBuilder() to construct.
    private PessoaProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PessoaProto() {
      nome_ = "";
      cidade_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return socket.data.Classes.internal_static_socket_data_PessoaProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return socket.data.Classes.internal_static_socket_data_PessoaProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              socket.data.Classes.PessoaProto.class, socket.data.Classes.PessoaProto.Builder.class);
    }

    public static final int NOME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nome_ = "";
    /**
     * <code>string nome = 1;</code>
     * @return The nome.
     */
    @java.lang.Override
    public java.lang.String getNome() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nome_ = s;
        return s;
      }
    }
    /**
     * <code>string nome = 1;</code>
     * @return The bytes for nome.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CIDADE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object cidade_ = "";
    /**
     * <code>string cidade = 2;</code>
     * @return The cidade.
     */
    @java.lang.Override
    public java.lang.String getCidade() {
      java.lang.Object ref = cidade_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cidade_ = s;
        return s;
      }
    }
    /**
     * <code>string cidade = 2;</code>
     * @return The bytes for cidade.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCidadeBytes() {
      java.lang.Object ref = cidade_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cidade_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TELEFONE_FIELD_NUMBER = 3;
    private long telefone_ = 0L;
    /**
     * <code>int64 telefone = 3;</code>
     * @return The telefone.
     */
    @java.lang.Override
    public long getTelefone() {
      return telefone_;
    }

    public static final int ANO_FIELD_NUMBER = 4;
    private int ano_ = 0;
    /**
     * <code>int32 ano = 4;</code>
     * @return The ano.
     */
    @java.lang.Override
    public int getAno() {
      return ano_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nome_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, nome_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(cidade_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, cidade_);
      }
      if (telefone_ != 0L) {
        output.writeInt64(3, telefone_);
      }
      if (ano_ != 0) {
        output.writeInt32(4, ano_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nome_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, nome_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(cidade_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, cidade_);
      }
      if (telefone_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, telefone_);
      }
      if (ano_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, ano_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof socket.data.Classes.PessoaProto)) {
        return super.equals(obj);
      }
      socket.data.Classes.PessoaProto other = (socket.data.Classes.PessoaProto) obj;

      if (!getNome()
          .equals(other.getNome())) return false;
      if (!getCidade()
          .equals(other.getCidade())) return false;
      if (getTelefone()
          != other.getTelefone()) return false;
      if (getAno()
          != other.getAno()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NOME_FIELD_NUMBER;
      hash = (53 * hash) + getNome().hashCode();
      hash = (37 * hash) + CIDADE_FIELD_NUMBER;
      hash = (53 * hash) + getCidade().hashCode();
      hash = (37 * hash) + TELEFONE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTelefone());
      hash = (37 * hash) + ANO_FIELD_NUMBER;
      hash = (53 * hash) + getAno();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static socket.data.Classes.PessoaProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static socket.data.Classes.PessoaProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static socket.data.Classes.PessoaProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static socket.data.Classes.PessoaProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static socket.data.Classes.PessoaProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static socket.data.Classes.PessoaProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static socket.data.Classes.PessoaProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static socket.data.Classes.PessoaProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static socket.data.Classes.PessoaProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static socket.data.Classes.PessoaProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static socket.data.Classes.PessoaProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static socket.data.Classes.PessoaProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(socket.data.Classes.PessoaProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code socket.data.PessoaProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:socket.data.PessoaProto)
        socket.data.Classes.PessoaProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return socket.data.Classes.internal_static_socket_data_PessoaProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return socket.data.Classes.internal_static_socket_data_PessoaProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                socket.data.Classes.PessoaProto.class, socket.data.Classes.PessoaProto.Builder.class);
      }

      // Construct using socket.data.Classes.PessoaProto.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        nome_ = "";
        cidade_ = "";
        telefone_ = 0L;
        ano_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return socket.data.Classes.internal_static_socket_data_PessoaProto_descriptor;
      }

      @java.lang.Override
      public socket.data.Classes.PessoaProto getDefaultInstanceForType() {
        return socket.data.Classes.PessoaProto.getDefaultInstance();
      }

      @java.lang.Override
      public socket.data.Classes.PessoaProto build() {
        socket.data.Classes.PessoaProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public socket.data.Classes.PessoaProto buildPartial() {
        socket.data.Classes.PessoaProto result = new socket.data.Classes.PessoaProto(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(socket.data.Classes.PessoaProto result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.nome_ = nome_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.cidade_ = cidade_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.telefone_ = telefone_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.ano_ = ano_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof socket.data.Classes.PessoaProto) {
          return mergeFrom((socket.data.Classes.PessoaProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(socket.data.Classes.PessoaProto other) {
        if (other == socket.data.Classes.PessoaProto.getDefaultInstance()) return this;
        if (!other.getNome().isEmpty()) {
          nome_ = other.nome_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getCidade().isEmpty()) {
          cidade_ = other.cidade_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getTelefone() != 0L) {
          setTelefone(other.getTelefone());
        }
        if (other.getAno() != 0) {
          setAno(other.getAno());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                nome_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                cidade_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                telefone_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                ano_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object nome_ = "";
      /**
       * <code>string nome = 1;</code>
       * @return The nome.
       */
      public java.lang.String getNome() {
        java.lang.Object ref = nome_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nome_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nome = 1;</code>
       * @return The bytes for nome.
       */
      public com.google.protobuf.ByteString
          getNomeBytes() {
        java.lang.Object ref = nome_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nome_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nome = 1;</code>
       * @param value The nome to set.
       * @return This builder for chaining.
       */
      public Builder setNome(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nome_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNome() {
        nome_ = getDefaultInstance().getNome();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 1;</code>
       * @param value The bytes for nome to set.
       * @return This builder for chaining.
       */
      public Builder setNomeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nome_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object cidade_ = "";
      /**
       * <code>string cidade = 2;</code>
       * @return The cidade.
       */
      public java.lang.String getCidade() {
        java.lang.Object ref = cidade_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cidade_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cidade = 2;</code>
       * @return The bytes for cidade.
       */
      public com.google.protobuf.ByteString
          getCidadeBytes() {
        java.lang.Object ref = cidade_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cidade_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cidade = 2;</code>
       * @param value The cidade to set.
       * @return This builder for chaining.
       */
      public Builder setCidade(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        cidade_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string cidade = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCidade() {
        cidade_ = getDefaultInstance().getCidade();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string cidade = 2;</code>
       * @param value The bytes for cidade to set.
       * @return This builder for chaining.
       */
      public Builder setCidadeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        cidade_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private long telefone_ ;
      /**
       * <code>int64 telefone = 3;</code>
       * @return The telefone.
       */
      @java.lang.Override
      public long getTelefone() {
        return telefone_;
      }
      /**
       * <code>int64 telefone = 3;</code>
       * @param value The telefone to set.
       * @return This builder for chaining.
       */
      public Builder setTelefone(long value) {

        telefone_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 telefone = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTelefone() {
        bitField0_ = (bitField0_ & ~0x00000004);
        telefone_ = 0L;
        onChanged();
        return this;
      }

      private int ano_ ;
      /**
       * <code>int32 ano = 4;</code>
       * @return The ano.
       */
      @java.lang.Override
      public int getAno() {
        return ano_;
      }
      /**
       * <code>int32 ano = 4;</code>
       * @param value The ano to set.
       * @return This builder for chaining.
       */
      public Builder setAno(int value) {

        ano_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ano = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAno() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ano_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:socket.data.PessoaProto)
    }

    // @@protoc_insertion_point(class_scope:socket.data.PessoaProto)
    private static final socket.data.Classes.PessoaProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new socket.data.Classes.PessoaProto();
    }

    public static socket.data.Classes.PessoaProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PessoaProto>
        PARSER = new com.google.protobuf.AbstractParser<PessoaProto>() {
      @java.lang.Override
      public PessoaProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PessoaProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PessoaProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public socket.data.Classes.PessoaProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ContatosProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:socket.data.ContatosProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.socket.data.PessoaProto dono = 1;</code>
     * @return Whether the dono field is set.
     */
    boolean hasDono();
    /**
     * <code>.socket.data.PessoaProto dono = 1;</code>
     * @return The dono.
     */
    socket.data.Classes.PessoaProto getDono();
    /**
     * <code>.socket.data.PessoaProto dono = 1;</code>
     */
    socket.data.Classes.PessoaProtoOrBuilder getDonoOrBuilder();

    /**
     * <code>repeated .socket.data.PessoaProto lista_de_contatos = 2;</code>
     */
    java.util.List<socket.data.Classes.PessoaProto> 
        getListaDeContatosList();
    /**
     * <code>repeated .socket.data.PessoaProto lista_de_contatos = 2;</code>
     */
    socket.data.Classes.PessoaProto getListaDeContatos(int index);
    /**
     * <code>repeated .socket.data.PessoaProto lista_de_contatos = 2;</code>
     */
    int getListaDeContatosCount();
    /**
     * <code>repeated .socket.data.PessoaProto lista_de_contatos = 2;</code>
     */
    java.util.List<? extends socket.data.Classes.PessoaProtoOrBuilder> 
        getListaDeContatosOrBuilderList();
    /**
     * <code>repeated .socket.data.PessoaProto lista_de_contatos = 2;</code>
     */
    socket.data.Classes.PessoaProtoOrBuilder getListaDeContatosOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code socket.data.ContatosProto}
   */
  public static final class ContatosProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:socket.data.ContatosProto)
      ContatosProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "",
        ContatosProto.class.getName());
    }
    // Use ContatosProto.newBuilder() to construct.
    private ContatosProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ContatosProto() {
      listaDeContatos_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return socket.data.Classes.internal_static_socket_data_ContatosProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return socket.data.Classes.internal_static_socket_data_ContatosProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              socket.data.Classes.ContatosProto.class, socket.data.Classes.ContatosProto.Builder.class);
    }

    private int bitField0_;
    public static final int DONO_FIELD_NUMBER = 1;
    private socket.data.Classes.PessoaProto dono_;
    /**
     * <code>.socket.data.PessoaProto dono = 1;</code>
     * @return Whether the dono field is set.
     */
    @java.lang.Override
    public boolean hasDono() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.socket.data.PessoaProto dono = 1;</code>
     * @return The dono.
     */
    @java.lang.Override
    public socket.data.Classes.PessoaProto getDono() {
      return dono_ == null ? socket.data.Classes.PessoaProto.getDefaultInstance() : dono_;
    }
    /**
     * <code>.socket.data.PessoaProto dono = 1;</code>
     */
    @java.lang.Override
    public socket.data.Classes.PessoaProtoOrBuilder getDonoOrBuilder() {
      return dono_ == null ? socket.data.Classes.PessoaProto.getDefaultInstance() : dono_;
    }

    public static final int LISTA_DE_CONTATOS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<socket.data.Classes.PessoaProto> listaDeContatos_;
    /**
     * <code>repeated .socket.data.PessoaProto lista_de_contatos = 2;</code>
     */
    @java.lang.Override
    public java.util.List<socket.data.Classes.PessoaProto> getListaDeContatosList() {
      return listaDeContatos_;
    }
    /**
     * <code>repeated .socket.data.PessoaProto lista_de_contatos = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends socket.data.Classes.PessoaProtoOrBuilder> 
        getListaDeContatosOrBuilderList() {
      return listaDeContatos_;
    }
    /**
     * <code>repeated .socket.data.PessoaProto lista_de_contatos = 2;</code>
     */
    @java.lang.Override
    public int getListaDeContatosCount() {
      return listaDeContatos_.size();
    }
    /**
     * <code>repeated .socket.data.PessoaProto lista_de_contatos = 2;</code>
     */
    @java.lang.Override
    public socket.data.Classes.PessoaProto getListaDeContatos(int index) {
      return listaDeContatos_.get(index);
    }
    /**
     * <code>repeated .socket.data.PessoaProto lista_de_contatos = 2;</code>
     */
    @java.lang.Override
    public socket.data.Classes.PessoaProtoOrBuilder getListaDeContatosOrBuilder(
        int index) {
      return listaDeContatos_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getDono());
      }
      for (int i = 0; i < listaDeContatos_.size(); i++) {
        output.writeMessage(2, listaDeContatos_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getDono());
      }
      for (int i = 0; i < listaDeContatos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, listaDeContatos_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof socket.data.Classes.ContatosProto)) {
        return super.equals(obj);
      }
      socket.data.Classes.ContatosProto other = (socket.data.Classes.ContatosProto) obj;

      if (hasDono() != other.hasDono()) return false;
      if (hasDono()) {
        if (!getDono()
            .equals(other.getDono())) return false;
      }
      if (!getListaDeContatosList()
          .equals(other.getListaDeContatosList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDono()) {
        hash = (37 * hash) + DONO_FIELD_NUMBER;
        hash = (53 * hash) + getDono().hashCode();
      }
      if (getListaDeContatosCount() > 0) {
        hash = (37 * hash) + LISTA_DE_CONTATOS_FIELD_NUMBER;
        hash = (53 * hash) + getListaDeContatosList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static socket.data.Classes.ContatosProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static socket.data.Classes.ContatosProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static socket.data.Classes.ContatosProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static socket.data.Classes.ContatosProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static socket.data.Classes.ContatosProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static socket.data.Classes.ContatosProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static socket.data.Classes.ContatosProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static socket.data.Classes.ContatosProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static socket.data.Classes.ContatosProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static socket.data.Classes.ContatosProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static socket.data.Classes.ContatosProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static socket.data.Classes.ContatosProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(socket.data.Classes.ContatosProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code socket.data.ContatosProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:socket.data.ContatosProto)
        socket.data.Classes.ContatosProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return socket.data.Classes.internal_static_socket_data_ContatosProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return socket.data.Classes.internal_static_socket_data_ContatosProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                socket.data.Classes.ContatosProto.class, socket.data.Classes.ContatosProto.Builder.class);
      }

      // Construct using socket.data.Classes.ContatosProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getDonoFieldBuilder();
          getListaDeContatosFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        dono_ = null;
        if (donoBuilder_ != null) {
          donoBuilder_.dispose();
          donoBuilder_ = null;
        }
        if (listaDeContatosBuilder_ == null) {
          listaDeContatos_ = java.util.Collections.emptyList();
        } else {
          listaDeContatos_ = null;
          listaDeContatosBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return socket.data.Classes.internal_static_socket_data_ContatosProto_descriptor;
      }

      @java.lang.Override
      public socket.data.Classes.ContatosProto getDefaultInstanceForType() {
        return socket.data.Classes.ContatosProto.getDefaultInstance();
      }

      @java.lang.Override
      public socket.data.Classes.ContatosProto build() {
        socket.data.Classes.ContatosProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public socket.data.Classes.ContatosProto buildPartial() {
        socket.data.Classes.ContatosProto result = new socket.data.Classes.ContatosProto(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(socket.data.Classes.ContatosProto result) {
        if (listaDeContatosBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            listaDeContatos_ = java.util.Collections.unmodifiableList(listaDeContatos_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.listaDeContatos_ = listaDeContatos_;
        } else {
          result.listaDeContatos_ = listaDeContatosBuilder_.build();
        }
      }

      private void buildPartial0(socket.data.Classes.ContatosProto result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.dono_ = donoBuilder_ == null
              ? dono_
              : donoBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof socket.data.Classes.ContatosProto) {
          return mergeFrom((socket.data.Classes.ContatosProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(socket.data.Classes.ContatosProto other) {
        if (other == socket.data.Classes.ContatosProto.getDefaultInstance()) return this;
        if (other.hasDono()) {
          mergeDono(other.getDono());
        }
        if (listaDeContatosBuilder_ == null) {
          if (!other.listaDeContatos_.isEmpty()) {
            if (listaDeContatos_.isEmpty()) {
              listaDeContatos_ = other.listaDeContatos_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureListaDeContatosIsMutable();
              listaDeContatos_.addAll(other.listaDeContatos_);
            }
            onChanged();
          }
        } else {
          if (!other.listaDeContatos_.isEmpty()) {
            if (listaDeContatosBuilder_.isEmpty()) {
              listaDeContatosBuilder_.dispose();
              listaDeContatosBuilder_ = null;
              listaDeContatos_ = other.listaDeContatos_;
              bitField0_ = (bitField0_ & ~0x00000002);
              listaDeContatosBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getListaDeContatosFieldBuilder() : null;
            } else {
              listaDeContatosBuilder_.addAllMessages(other.listaDeContatos_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getDonoFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                socket.data.Classes.PessoaProto m =
                    input.readMessage(
                        socket.data.Classes.PessoaProto.parser(),
                        extensionRegistry);
                if (listaDeContatosBuilder_ == null) {
                  ensureListaDeContatosIsMutable();
                  listaDeContatos_.add(m);
                } else {
                  listaDeContatosBuilder_.addMessage(m);
                }
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private socket.data.Classes.PessoaProto dono_;
      private com.google.protobuf.SingleFieldBuilder<
          socket.data.Classes.PessoaProto, socket.data.Classes.PessoaProto.Builder, socket.data.Classes.PessoaProtoOrBuilder> donoBuilder_;
      /**
       * <code>.socket.data.PessoaProto dono = 1;</code>
       * @return Whether the dono field is set.
       */
      public boolean hasDono() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.socket.data.PessoaProto dono = 1;</code>
       * @return The dono.
       */
      public socket.data.Classes.PessoaProto getDono() {
        if (donoBuilder_ == null) {
          return dono_ == null ? socket.data.Classes.PessoaProto.getDefaultInstance() : dono_;
        } else {
          return donoBuilder_.getMessage();
        }
      }
      /**
       * <code>.socket.data.PessoaProto dono = 1;</code>
       */
      public Builder setDono(socket.data.Classes.PessoaProto value) {
        if (donoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dono_ = value;
        } else {
          donoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.socket.data.PessoaProto dono = 1;</code>
       */
      public Builder setDono(
          socket.data.Classes.PessoaProto.Builder builderForValue) {
        if (donoBuilder_ == null) {
          dono_ = builderForValue.build();
        } else {
          donoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.socket.data.PessoaProto dono = 1;</code>
       */
      public Builder mergeDono(socket.data.Classes.PessoaProto value) {
        if (donoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            dono_ != null &&
            dono_ != socket.data.Classes.PessoaProto.getDefaultInstance()) {
            getDonoBuilder().mergeFrom(value);
          } else {
            dono_ = value;
          }
        } else {
          donoBuilder_.mergeFrom(value);
        }
        if (dono_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.socket.data.PessoaProto dono = 1;</code>
       */
      public Builder clearDono() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dono_ = null;
        if (donoBuilder_ != null) {
          donoBuilder_.dispose();
          donoBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.socket.data.PessoaProto dono = 1;</code>
       */
      public socket.data.Classes.PessoaProto.Builder getDonoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getDonoFieldBuilder().getBuilder();
      }
      /**
       * <code>.socket.data.PessoaProto dono = 1;</code>
       */
      public socket.data.Classes.PessoaProtoOrBuilder getDonoOrBuilder() {
        if (donoBuilder_ != null) {
          return donoBuilder_.getMessageOrBuilder();
        } else {
          return dono_ == null ?
              socket.data.Classes.PessoaProto.getDefaultInstance() : dono_;
        }
      }
      /**
       * <code>.socket.data.PessoaProto dono = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          socket.data.Classes.PessoaProto, socket.data.Classes.PessoaProto.Builder, socket.data.Classes.PessoaProtoOrBuilder> 
          getDonoFieldBuilder() {
        if (donoBuilder_ == null) {
          donoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              socket.data.Classes.PessoaProto, socket.data.Classes.PessoaProto.Builder, socket.data.Classes.PessoaProtoOrBuilder>(
                  getDono(),
                  getParentForChildren(),
                  isClean());
          dono_ = null;
        }
        return donoBuilder_;
      }

      private java.util.List<socket.data.Classes.PessoaProto> listaDeContatos_ =
        java.util.Collections.emptyList();
      private void ensureListaDeContatosIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          listaDeContatos_ = new java.util.ArrayList<socket.data.Classes.PessoaProto>(listaDeContatos_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          socket.data.Classes.PessoaProto, socket.data.Classes.PessoaProto.Builder, socket.data.Classes.PessoaProtoOrBuilder> listaDeContatosBuilder_;

      /**
       * <code>repeated .socket.data.PessoaProto lista_de_contatos = 2;</code>
       */
      public java.util.List<socket.data.Classes.PessoaProto> getListaDeContatosList() {
        if (listaDeContatosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(listaDeContatos_);
        } else {
          return listaDeContatosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .socket.data.PessoaProto lista_de_contatos = 2;</code>
       */
      public int getListaDeContatosCount() {
        if (listaDeContatosBuilder_ == null) {
          return listaDeContatos_.size();
        } else {
          return listaDeContatosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .socket.data.PessoaProto lista_de_contatos = 2;</code>
       */
      public socket.data.Classes.PessoaProto getListaDeContatos(int index) {
        if (listaDeContatosBuilder_ == null) {
          return listaDeContatos_.get(index);
        } else {
          return listaDeContatosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .socket.data.PessoaProto lista_de_contatos = 2;</code>
       */
      public Builder setListaDeContatos(
          int index, socket.data.Classes.PessoaProto value) {
        if (listaDeContatosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListaDeContatosIsMutable();
          listaDeContatos_.set(index, value);
          onChanged();
        } else {
          listaDeContatosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .socket.data.PessoaProto lista_de_contatos = 2;</code>
       */
      public Builder setListaDeContatos(
          int index, socket.data.Classes.PessoaProto.Builder builderForValue) {
        if (listaDeContatosBuilder_ == null) {
          ensureListaDeContatosIsMutable();
          listaDeContatos_.set(index, builderForValue.build());
          onChanged();
        } else {
          listaDeContatosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .socket.data.PessoaProto lista_de_contatos = 2;</code>
       */
      public Builder addListaDeContatos(socket.data.Classes.PessoaProto value) {
        if (listaDeContatosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListaDeContatosIsMutable();
          listaDeContatos_.add(value);
          onChanged();
        } else {
          listaDeContatosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .socket.data.PessoaProto lista_de_contatos = 2;</code>
       */
      public Builder addListaDeContatos(
          int index, socket.data.Classes.PessoaProto value) {
        if (listaDeContatosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListaDeContatosIsMutable();
          listaDeContatos_.add(index, value);
          onChanged();
        } else {
          listaDeContatosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .socket.data.PessoaProto lista_de_contatos = 2;</code>
       */
      public Builder addListaDeContatos(
          socket.data.Classes.PessoaProto.Builder builderForValue) {
        if (listaDeContatosBuilder_ == null) {
          ensureListaDeContatosIsMutable();
          listaDeContatos_.add(builderForValue.build());
          onChanged();
        } else {
          listaDeContatosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .socket.data.PessoaProto lista_de_contatos = 2;</code>
       */
      public Builder addListaDeContatos(
          int index, socket.data.Classes.PessoaProto.Builder builderForValue) {
        if (listaDeContatosBuilder_ == null) {
          ensureListaDeContatosIsMutable();
          listaDeContatos_.add(index, builderForValue.build());
          onChanged();
        } else {
          listaDeContatosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .socket.data.PessoaProto lista_de_contatos = 2;</code>
       */
      public Builder addAllListaDeContatos(
          java.lang.Iterable<? extends socket.data.Classes.PessoaProto> values) {
        if (listaDeContatosBuilder_ == null) {
          ensureListaDeContatosIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, listaDeContatos_);
          onChanged();
        } else {
          listaDeContatosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .socket.data.PessoaProto lista_de_contatos = 2;</code>
       */
      public Builder clearListaDeContatos() {
        if (listaDeContatosBuilder_ == null) {
          listaDeContatos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          listaDeContatosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .socket.data.PessoaProto lista_de_contatos = 2;</code>
       */
      public Builder removeListaDeContatos(int index) {
        if (listaDeContatosBuilder_ == null) {
          ensureListaDeContatosIsMutable();
          listaDeContatos_.remove(index);
          onChanged();
        } else {
          listaDeContatosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .socket.data.PessoaProto lista_de_contatos = 2;</code>
       */
      public socket.data.Classes.PessoaProto.Builder getListaDeContatosBuilder(
          int index) {
        return getListaDeContatosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .socket.data.PessoaProto lista_de_contatos = 2;</code>
       */
      public socket.data.Classes.PessoaProtoOrBuilder getListaDeContatosOrBuilder(
          int index) {
        if (listaDeContatosBuilder_ == null) {
          return listaDeContatos_.get(index);  } else {
          return listaDeContatosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .socket.data.PessoaProto lista_de_contatos = 2;</code>
       */
      public java.util.List<? extends socket.data.Classes.PessoaProtoOrBuilder> 
           getListaDeContatosOrBuilderList() {
        if (listaDeContatosBuilder_ != null) {
          return listaDeContatosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(listaDeContatos_);
        }
      }
      /**
       * <code>repeated .socket.data.PessoaProto lista_de_contatos = 2;</code>
       */
      public socket.data.Classes.PessoaProto.Builder addListaDeContatosBuilder() {
        return getListaDeContatosFieldBuilder().addBuilder(
            socket.data.Classes.PessoaProto.getDefaultInstance());
      }
      /**
       * <code>repeated .socket.data.PessoaProto lista_de_contatos = 2;</code>
       */
      public socket.data.Classes.PessoaProto.Builder addListaDeContatosBuilder(
          int index) {
        return getListaDeContatosFieldBuilder().addBuilder(
            index, socket.data.Classes.PessoaProto.getDefaultInstance());
      }
      /**
       * <code>repeated .socket.data.PessoaProto lista_de_contatos = 2;</code>
       */
      public java.util.List<socket.data.Classes.PessoaProto.Builder> 
           getListaDeContatosBuilderList() {
        return getListaDeContatosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          socket.data.Classes.PessoaProto, socket.data.Classes.PessoaProto.Builder, socket.data.Classes.PessoaProtoOrBuilder> 
          getListaDeContatosFieldBuilder() {
        if (listaDeContatosBuilder_ == null) {
          listaDeContatosBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              socket.data.Classes.PessoaProto, socket.data.Classes.PessoaProto.Builder, socket.data.Classes.PessoaProtoOrBuilder>(
                  listaDeContatos_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          listaDeContatos_ = null;
        }
        return listaDeContatosBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:socket.data.ContatosProto)
    }

    // @@protoc_insertion_point(class_scope:socket.data.ContatosProto)
    private static final socket.data.Classes.ContatosProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new socket.data.Classes.ContatosProto();
    }

    public static socket.data.Classes.ContatosProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ContatosProto>
        PARSER = new com.google.protobuf.AbstractParser<ContatosProto>() {
      @java.lang.Override
      public ContatosProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ContatosProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ContatosProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public socket.data.Classes.ContatosProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_socket_data_PessoaProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_socket_data_PessoaProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_socket_data_ContatosProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_socket_data_ContatosProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rclasses.proto\022\013socket.data\"J\n\013PessoaPr" +
      "oto\022\014\n\004nome\030\001 \001(\t\022\016\n\006cidade\030\002 \001(\t\022\020\n\010tel" +
      "efone\030\003 \001(\003\022\013\n\003ano\030\004 \001(\005\"l\n\rContatosProt" +
      "o\022&\n\004dono\030\001 \001(\0132\030.socket.data.PessoaProt" +
      "o\0223\n\021lista_de_contatos\030\002 \003(\0132\030.socket.da" +
      "ta.PessoaProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_socket_data_PessoaProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_socket_data_PessoaProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_socket_data_PessoaProto_descriptor,
        new java.lang.String[] { "Nome", "Cidade", "Telefone", "Ano", });
    internal_static_socket_data_ContatosProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_socket_data_ContatosProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_socket_data_ContatosProto_descriptor,
        new java.lang.String[] { "Dono", "ListaDeContatos", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
